version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: muscleup-mysql
    restart: always
    environment:
      MYSQL_DATABASE: muscleup
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: muscleup-app
    ports:
      - "7080:7070"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/muscleup_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: computer

volumes:
  db_data:
